"""SQL migration converter module.

This module provides a conversion pipeline for transforming MySQL SQL statements
into PostgreSQL-compatible SQL using SQLGlot.
"""

from __future__ import annotations

import re
from typing import Any, Dict

from sqlglot import transpile
from sqlglot.errors import ParseError

SUPPORTED_DIALECTS = {
    "mysql",
    "postgres",
    "postgresql",
}

MYSQL_TO_POSTGRES_TYPES: Dict[str, str] = {
    "DATETIME": "TIMESTAMP",
    "LONGTEXT": "TEXT",
    "TINYINT": "SMALLINT",
    "DOUBLE": "DOUBLE PRECISION",
    "MEDIUMINT": "INTEGER",
    "INT": "INTEGER",
    "INTEGER": "INTEGER",
    "BIGINT": "BIGINT",
    "SMALLINT": "SMALLINT",
    "VARCHAR": "VARCHAR",
    "CHAR": "CHAR",
    "TEXT": "TEXT",
    "BLOB": "BYTEA",
    "MEDIUMTEXT": "TEXT",
    "FLOAT": "REAL",
    "DECIMAL": "DECIMAL",
}


def _normalize_dialect(dialect: str) -> str:
    """Normalize common SQL dialect aliases for use with SQLGlot."""
    normalized = dialect.strip().lower()
    if normalized == "postgresql":
        return "postgres"
    return normalized


def _validate_dialect(dialect: str) -> bool:
    """Return True when the dialect is supported by this converter."""
    return _normalize_dialect(dialect) in {"mysql", "postgres"}


def map_datatypes(sql: str) -> str:
    """Map MySQL data types to PostgreSQL-compatible equivalents."""
    mapped_sql = sql
    for mysql_type, postgres_type in MYSQL_TO_POSTGRES_TYPES.items():
        pattern = rf"\b{re.escape(mysql_type)}\b"
        mapped_sql = re.sub(pattern, postgres_type, mapped_sql, flags=re.IGNORECASE)
    return mapped_sql


def apply_custom_transformations(sql: str) -> str:
    """Apply custom syntactic transformations for PostgreSQL compatibility."""
    transformed_sql = sql

    # Remove MySQL identifier delimiters.
    transformed_sql = transformed_sql.replace("`", "")

    # Remove AUTO_INCREMENT clauses that PostgreSQL does not support directly.
    transformed_sql = re.sub(r"\bAUTO_INCREMENT\b", "", transformed_sql, flags=re.IGNORECASE)

    # Remove MySQL engine and charset declarations.
    transformed_sql = re.sub(r"ENGINE\s*=\s*\w+", "", transformed_sql, flags=re.IGNORECASE)
    transformed_sql = re.sub(r"DEFAULT\s+CHARSET\s*=\s*\w+", "", transformed_sql, flags=re.IGNORECASE)

    # Remove unsigned keywords, PostgreSQL handles signedness differently.
    transformed_sql = re.sub(r"\bUNSIGNED\b", "", transformed_sql, flags=re.IGNORECASE)

    # Clean up whitespace generated by replacement operations.
    transformed_sql = re.sub(r"\s{2,}", " ", transformed_sql)
    transformed_sql = re.sub(r"\(\s+", "(", transformed_sql)
    transformed_sql = re.sub(r"\s+\)", ")", transformed_sql)

    return transformed_sql.strip()


def convert_sql(sql: str, source: str = "mysql", target: str = "postgres") -> Dict[str, Any]:
    """Convert SQL from one dialect into a target dialect.

    The conversion pipeline includes:
      1. Validate input and dialect support
      2. Apply custom syntax transformations
      3. Map MySQL-specific datatypes
      4. Transpile SQL using SQLGlot
      5. Perform final cleanup

    Returns a structured JSON-style response.
    """
    if not isinstance(sql, str) or not sql.strip():
        return {"success": False, "error": "SQL input must be a non-empty string."}

    normalized_source = _normalize_dialect(source)
    normalized_target = _normalize_dialect(target)

    if not _validate_dialect(normalized_source):
        return {"success": False, "error": f"Unsupported source dialect: {source}."}

    if not _validate_dialect(normalized_target):
        return {"success": False, "error": f"Unsupported target dialect: {target}."}

    cleaned_sql = sql.strip()
    cleaned_sql = apply_custom_transformations(cleaned_sql)
    cleaned_sql = map_datatypes(cleaned_sql)

    try:
        converted_list = transpile(cleaned_sql, read=normalized_source, write=normalized_target)
        if not converted_list:
            raise ValueError("SQLGlot returned an empty conversion result.")

        converted_sql = converted_list[0]
        converted_sql = apply_custom_transformations(converted_sql)

        return {"success": True, "converted_sql": converted_sql}

    except ParseError as parse_error:
        return {"success": False, "error": f"SQL parse error: {parse_error}"}
    except Exception as error:
        return {"success": False, "error": f"Conversion failed: {error}"}


if __name__ == "__main__":
    sample_sql = '''CREATE TABLE `users` (
      `id` INT NOT NULL AUTO_INCREMENT,
      `name` VARCHAR(100) NOT NULL,
      `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
      `status` TINYINT DEFAULT 0,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;'''

    response = convert_sql(sample_sql)

    if response["success"]:
        print("Converted SQL:")
        print(response["converted_sql"])
    else:
        print("Conversion failed:")
        print(response["error"])
