import re
from typing import Callable

SUPPORTED_DIALECTS = {"mysql", "postgresql", "oracle", "sqlite"}


def convert_sql(sql_text: str, source_dialect: str, target_dialect: str) -> str:
    """Convert SQL text from one dialect to another."""
    if not sql_text:
        return ""

    source = _normalize_dialect(source_dialect)
    target = _normalize_dialect(target_dialect)

    if source == target:
        return sql_text.strip()

    sql = _normalize_line_endings(sql_text)
    sql = _strip_comments(sql)
    sql = _clean_mysql_artifacts(sql)
    sql = _convert_quotes(sql, source, target)
    sql = _convert_builtin_functions(sql, source, target)
    sql = _convert_data_types(sql, source, target)
    sql = _convert_auto_increment(sql, source, target)
    sql = _convert_limit_offset(sql, source, target)
    sql = _convert_identity_and_sequence(sql, source, target)
    sql = _final_cleanup(sql, target)

    return sql.strip()


def _normalize_dialect(name: str) -> str:
    dialect = str(name or "").strip().lower()

    if dialect in {"postgres", "postgresql"}:
        return "postgresql"
    if dialect in {"sqlite", "sqlite3"}:
        return "sqlite"
    if dialect == "mysql":
        return "mysql"
    if dialect == "oracle":
        return "oracle"

    raise ValueError(f"Unsupported SQL dialect: {name}")


def _normalize_line_endings(sql: str) -> str:
    return sql.replace("\r\n", "\n").replace("\r", "\n")


def _strip_comments(sql: str) -> str:
    sql = re.sub(r'/\*.*?\*/', '', sql, flags=re.DOTALL)
    sql = re.sub(r'--.*?(\n|$)', '\1', sql)
    return sql


def _clean_mysql_artifacts(sql: str) -> str:
    sql = re.sub(r'ENGINE\s*=\s*[^\s;]+', '', sql, flags=re.IGNORECASE)
    sql = re.sub(r'DEFAULT\s+CHARSET\s*=\s*[^\s;]+', '', sql, flags=re.IGNORECASE)
    sql = re.sub(r'COLLATE\s+[^\s;]+', '', sql, flags=re.IGNORECASE)
    sql = re.sub(r'UNSIGNED', '', sql, flags=re.IGNORECASE)
    sql = re.sub(r'AUTO_INCREMENT\s*=\s*\d+', '', sql, flags=re.IGNORECASE)
    sql = re.sub(r'\s{2,}', ' ', sql)
    return sql


def _convert_quotes(sql: str, source: str, target: str) -> str:
    if source == target:
        return sql

    if target == "mysql":
        sql = sql.replace('"', '`')
        sql = re.sub(r'`([^`]+)`', r'`\1`', sql)
    elif target in {"postgresql", "oracle"}:
        sql = sql.replace('`', '"')
    elif target == "sqlite":
        sql = sql.replace('`', '"')
    return sql


def _convert_builtin_functions(sql: str, source: str, target: str) -> str:
    if source == "mysql" and target == "postgresql":
        sql = re.sub(r'\bIFNULL\s*\(', 'COALESCE(', sql, flags=re.IGNORECASE)
    if source == "postgresql" and target == "mysql":
        sql = re.sub(r'\bNOW\s*\(\s*\)', 'NOW()', sql, flags=re.IGNORECASE)
    if source == "oracle" and target == "mysql":
        sql = re.sub(r'\bSYSDATE\b', 'CURRENT_TIMESTAMP', sql, flags=re.IGNORECASE)
    if source == "mysql" and target == "oracle":
        sql = re.sub(r'\bIFNULL\s*\(', 'NVL(', sql, flags=re.IGNORECASE)
    return sql


def _convert_data_types(sql: str, source: str, target: str) -> str:
    converters = {
        ("mysql", "postgresql"): _map_mysql_to_postgresql_types,
        ("mysql", "sqlite"): _map_mysql_to_sqlite_types,
        ("mysql", "oracle"): _map_mysql_to_oracle_types,
        ("postgresql", "mysql"): _map_postgresql_to_mysql_types,
        ("postgresql", "sqlite"): _map_postgresql_to_sqlite_types,
        ("postgresql", "oracle"): _map_postgresql_to_oracle_types,
        ("sqlite", "mysql"): _map_sqlite_to_mysql_types,
        ("sqlite", "postgresql"): _map_sqlite_to_postgresql_types,
        ("sqlite", "oracle"): _map_sqlite_to_oracle_types,
        ("oracle", "mysql"): _map_oracle_to_mysql_types,
        ("oracle", "postgresql"): _map_oracle_to_postgresql_types,
        ("oracle", "sqlite"): _map_oracle_to_sqlite_types,
    }

    converter = converters.get((source, target))
    return converter(sql) if converter else sql


def _convert_auto_increment(sql: str, source: str, target: str) -> str:
    if source == "mysql" and target == "postgresql":
        sql = re.sub(r'\bBIGINT\s*\(\s*\d+\s*\)\s+AUTO_INCREMENT', 'BIGSERIAL', sql, flags=re.IGNORECASE)
        sql = re.sub(r'\b(INT|INTEGER|SMALLINT|MEDIUMINT|TINYINT)\s*\(\s*\d+\s*\)\s+AUTO_INCREMENT', 'SERIAL', sql, flags=re.IGNORECASE)
        sql = re.sub(r'\bAUTO_INCREMENT\b', '', sql, flags=re.IGNORECASE)

    if source == "mysql" and target == "sqlite":
        sql = re.sub(r'\bAUTO_INCREMENT\b', 'AUTOINCREMENT', sql, flags=re.IGNORECASE)
        sql = re.sub(r'\bINT\s*\(\s*\d+\s*\)\b', 'INTEGER', sql, flags=re.IGNORECASE)

    if source == "mysql" and target == "oracle":
        sql = re.sub(r'\bBIGINT\s*\(\s*\d+\s*\)\s+AUTO_INCREMENT', 'NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY', sql, flags=re.IGNORECASE)
        sql = re.sub(r'\b(INT|INTEGER|SMALLINT|MEDIUMINT|TINYINT)\s*\(\s*\d+\s*\)\s+AUTO_INCREMENT', 'NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY', sql, flags=re.IGNORECASE)
        sql = re.sub(r'\bAUTO_INCREMENT\b', '', sql, flags=re.IGNORECASE)

    if source == "postgresql" and target == "mysql":
        sql = re.sub(r'\bBIGSERIAL\b', 'BIGINT AUTO_INCREMENT', sql, flags=re.IGNORECASE)
        sql = re.sub(r'\bSERIAL\b', 'INT AUTO_INCREMENT', sql, flags=re.IGNORECASE)

    if source == "postgresql" and target == "sqlite":
        sql = re.sub(r'\bBIGSERIAL\b', 'INTEGER', sql, flags=re.IGNORECASE)
        sql = re.sub(r'\bSERIAL\b', 'INTEGER', sql, flags=re.IGNORECASE)

    if source == "postgresql" and target == "oracle":
        sql = re.sub(r'\bBIGSERIAL\b', 'NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY', sql, flags=re.IGNORECASE)
        sql = re.sub(r'\bSERIAL\b', 'NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY', sql, flags=re.IGNORECASE)

    if source == "oracle" and target == "mysql":
        sql = re.sub(r'GENERATED\s+BY\s+DEFAULT\s+ON\s+NULL\s+AS\s+IDENTITY', 'AUTO_INCREMENT', sql, flags=re.IGNORECASE)

    return sql


def _convert_limit_offset(sql: str, source: str, target: str) -> str:
    if source == "mysql" and target == "postgresql":
        sql = re.sub(r'LIMIT\s*(\d+)\s*,\s*(\d+)', r'LIMIT \2 OFFSET \1', sql, flags=re.IGNORECASE)
    if source == "postgresql" and target == "mysql":
        sql = re.sub(r'LIMIT\s*(\d+)\s+OFFSET\s+(\d+)', r'LIMIT \2, \1', sql, flags=re.IGNORECASE)
    if target == "oracle":
        sql = re.sub(r'LIMIT\s*(\d+)\s+OFFSET\s*(\d+)', r'OFFSET \2 ROWS FETCH NEXT \1 ROWS ONLY', sql, flags=re.IGNORECASE)
        sql = re.sub(r'LIMIT\s*(\d+)', r'FETCH FIRST \1 ROWS ONLY', sql, flags=re.IGNORECASE)
    return sql


def _convert_identity_and_sequence(sql: str, source: str, target: str) -> str:
    if source == "oracle" and target == "postgresql":
        sql = re.sub(r'NUMBER\s+GENERATED\s+BY\s+DEFAULT\s+ON\s+NULL\s+AS\s+IDENTITY', 'SERIAL', sql, flags=re.IGNORECASE)
    return sql


def _final_cleanup(sql: str, target: str) -> str:
    sql = re.sub(r'\s+;', ';', sql)
    sql = sql.replace('``', '`')
    sql = re.sub(r'\s{2,}', ' ', sql)
    sql = sql.strip()
    return sql


def _map_mysql_to_postgresql_types(sql: str) -> str:
    replacements = {
        r'\bTINYINT\s*\(\s*1\s*\)': 'BOOLEAN',
        r'\bDATETIME\b': 'TIMESTAMP',
        r'\bDOUBLE\b': 'DOUBLE PRECISION',
        r'\bMEDIUMTEXT\b': 'TEXT',
        r'\bLONGTEXT\b': 'TEXT',
        r'\bJSON\b': 'JSONB',
        r'\bDOUBLE PRECISION\b': 'DOUBLE PRECISION',
        r'\bINT\s*\(\s*\d+\s*\)': 'INTEGER',
        r'\bBIGINT\s*\(\s*\d+\s*\)': 'BIGINT',
        r'\bSMALLINT\s*\(\s*\d+\s*\)': 'SMALLINT',
        r'\bFLOAT\b': 'REAL',
        r'\bVARCHAR2\b': 'VARCHAR',
    }
    return _multi_replace(sql, replacements)


def _map_mysql_to_sqlite_types(sql: str) -> str:
    replacements = {
        r'\bTINYINT\s*\(\s*1\s*\)': 'INTEGER',
        r'\bINT\s*\(\s*\d+\s*\)': 'INTEGER',
        r'\bBIGINT\s*\(\s*\d+\s*\)': 'INTEGER',
        r'\bMEDIUMINT\b': 'INTEGER',
        r'\bSMALLINT\b': 'INTEGER',
        r'\bDOUBLE\b': 'REAL',
        r'\bFLOAT\b': 'REAL',
        r'\bDECIMAL\b': 'REAL',
        r'\bDATETIME\b': 'TEXT',
        r'\bJSON\b': 'TEXT',
        r'\bLONGTEXT\b': 'TEXT',
        r'\bMEDIUMTEXT\b': 'TEXT',
        r'\bTEXT\b': 'TEXT',
    }
    return _multi_replace(sql, replacements)


def _map_mysql_to_oracle_types(sql: str) -> str:
    replacements = {
        r'\bTINYINT\s*\(\s*1\s*\)': 'NUMBER(1)',
        r'\bINT\s*\(\s*\d+\s*\)': 'NUMBER',
        r'\bBIGINT\s*\(\s*\d+\s*\)': 'NUMBER',
        r'\bSMALLINT\b': 'NUMBER',
        r'\bMEDIUMINT\b': 'NUMBER',
        r'\bDOUBLE\b': 'BINARY_DOUBLE',
        r'\bFLOAT\b': 'BINARY_FLOAT',
        r'\bDECIMAL\b': 'NUMBER',
        r'\bDATETIME\b': 'TIMESTAMP',
        r'\bJSON\b': 'CLOB',
        r'\bTEXT\b': 'CLOB',
        r'\bVARCHAR\b': 'VARCHAR2',
    }
    return _multi_replace(sql, replacements)


def _map_postgresql_to_mysql_types(sql: str) -> str:
    replacements = {
        r'\bSERIAL\b': 'INT AUTO_INCREMENT',
        r'\bBIGSERIAL\b': 'BIGINT AUTO_INCREMENT',
        r'\bBOOLEAN\b': 'TINYINT(1)',
        r'\bDOUBLE PRECISION\b': 'DOUBLE',
        r'\bREAL\b': 'FLOAT',
        r'\bNUMERIC\b': 'DECIMAL',
        r'\bJSONB\b': 'JSON',
        r'\bBYTEA\b': 'BLOB',
        r'\bTIMESTAMP\b': 'DATETIME',
        r'\bTEXT\b': 'TEXT',
        r'\bVARCHAR2\b': 'VARCHAR',
    }
    return _multi_replace(sql, replacements)


def _map_postgresql_to_sqlite_types(sql: str) -> str:
    replacements = {
        r'\bSERIAL\b': 'INTEGER',
        r'\bBIGSERIAL\b': 'INTEGER',
        r'\bBOOLEAN\b': 'INTEGER',
        r'\bDOUBLE PRECISION\b': 'REAL',
        r'\bREAL\b': 'REAL',
        r'\bNUMERIC\b': 'REAL',
        r'\bJSONB\b': 'TEXT',
        r'\bJSON\b': 'TEXT',
        r'\bBYTEA\b': 'BLOB',
        r'\bTIMESTAMP\b': 'TEXT',
        r'\bTEXT\b': 'TEXT',
    }
    return _multi_replace(sql, replacements)


def _map_postgresql_to_oracle_types(sql: str) -> str:
    replacements = {
        r'\bSERIAL\b': 'NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY',
        r'\bBIGSERIAL\b': 'NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY',
        r'\bBOOLEAN\b': 'NUMBER(1)',
        r'\bDOUBLE PRECISION\b': 'BINARY_DOUBLE',
        r'\bREAL\b': 'BINARY_FLOAT',
        r'\bNUMERIC\b': 'NUMBER',
        r'\bJSONB\b': 'CLOB',
        r'\bJSON\b': 'CLOB',
        r'\bBYTEA\b': 'BLOB',
        r'\bTIMESTAMP\b': 'TIMESTAMP',
        r'\bTEXT\b': 'CLOB',
    }
    return _multi_replace(sql, replacements)


def _map_sqlite_to_mysql_types(sql: str) -> str:
    replacements = {
        r'\bINTEGER\b': 'INT',
        r'\bBOOLEAN\b': 'TINYINT(1)',
        r'\bREAL\b': 'DOUBLE',
        r'\bNUMERIC\b': 'DECIMAL',
        r'\bTEXT\b': 'TEXT',
        r'\bBLOB\b': 'BLOB',
    }
    return _multi_replace(sql, replacements)


def _map_sqlite_to_postgresql_types(sql: str) -> str:
    replacements = {
        r'\bINTEGER\b': 'BIGINT',
        r'\bREAL\b': 'DOUBLE PRECISION',
        r'\bNUMERIC\b': 'NUMERIC',
        r'\bTEXT\b': 'TEXT',
        r'\bBLOB\b': 'BYTEA',
    }
    return _multi_replace(sql, replacements)


def _map_sqlite_to_oracle_types(sql: str) -> str:
    replacements = {
        r'\bINTEGER\b': 'NUMBER',
        r'\bREAL\b': 'BINARY_DOUBLE',
        r'\bNUMERIC\b': 'NUMBER',
        r'\bTEXT\b': 'CLOB',
        r'\bBLOB\b': 'BLOB',
    }
    return _multi_replace(sql, replacements)


def _map_oracle_to_mysql_types(sql: str) -> str:
    replacements = {
        r'\bNUMBER\s*\(\s*1\s*\)': 'TINYINT(1)',
        r'\bNUMBER\b': 'INT',
        r'\bBINARY_DOUBLE\b': 'DOUBLE',
        r'\bBINARY_FLOAT\b': 'FLOAT',
        r'\bCLOB\b': 'TEXT',
        r'\bVARCHAR2\b': 'VARCHAR',
        r'\bTIMESTAMP\b': 'DATETIME',
    }
    return _multi_replace(sql, replacements)


def _map_oracle_to_postgresql_types(sql: str) -> str:
    replacements = {
        r'\bNUMBER\s*\(\s*1\s*\)': 'BOOLEAN',
        r'\bNUMBER\b': 'INTEGER',
        r'\bBINARY_DOUBLE\b': 'DOUBLE PRECISION',
        r'\bBINARY_FLOAT\b': 'REAL',
        r'\bCLOB\b': 'TEXT',
        r'\bVARCHAR2\b': 'VARCHAR',
        r'\bTIMESTAMP\b': 'TIMESTAMP',
    }
    return _multi_replace(sql, replacements)


def _map_oracle_to_sqlite_types(sql: str) -> str:
    replacements = {
        r'\bNUMBER\s*\(\s*1\s*\)': 'INTEGER',
        r'\bNUMBER\b': 'INTEGER',
        r'\bBINARY_DOUBLE\b': 'REAL',
        r'\bBINARY_FLOAT\b': 'REAL',
        r'\bCLOB\b': 'TEXT',
        r'\bVARCHAR2\b': 'TEXT',
        r'\bTIMESTAMP\b': 'TEXT',
    }
    return _multi_replace(sql, replacements)


def _multi_replace(sql: str, replacements: dict) -> str:
    for pattern, replacement in replacements.items():
        sql = re.sub(pattern, replacement, sql, flags=re.IGNORECASE)
    return sql


if __name__ == '__main__':
    sample = '''
    CREATE TABLE `customers` (
        `id` INT(11) NOT NULL AUTO_INCREMENT,
        `name` VARCHAR(255) NOT NULL,
        `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    '''

    print(convert_sql(sample, 'mysql', 'postgresql'))
